- type: job
  id: Logist
  name: job-name-logist
  description: job-description-logist
  playTimeTracker: JobLogist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000 #5 hours
    - !type:OverallPlaytimeRequirement
      time: 25200 #7 hrs
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
  weight: 10
  startingGear: LogistGear
  icon: "JobIconLogist"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: LogistGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
